[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PMAT"
authors = [{name = "Spencer Riley", email = "academic@sriley.dev"}]
dynamic = ["version", "description"]
