name: automerge
on: [push]
#   workflow_run:
#     branches: [master]
#     workflows: ["Docker Run"]
#     types: 
#       - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: 8BitJonny/gh-get-current-pr@1.1.0
      id: PR
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        filterOutClosed: true
    - name: print
      run: echo "Your PR is ${{ steps.PR.outputs.number }} and its JSON is${{ steps.PR.outputs.pr }}"
    - name: automerge
      if: contains('${{ steps.PR.outputs.pr }}', 'pmat-deploy') && contains('${{ steps.PR.outputs.pr }}', 'automerge')
      uses: "pascalgn/automerge-action@v0.14.2"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        PULL_REQUEST: "${{ steps.PR.outputs.number }}"
