name: Update Changelog
on:
  push:
    paths:
      - "util/changelog.yml"
jobs:
  branch:
    runs-on: ubuntu-latest
    name: Update changelog
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Update Changelog
      run: |
        python -m pip install pyyaml
        cd util/ && python update_docs.py -t changelog
    - name: Run GitHub File Sync
      uses: adrianjost/files-sync-action@v1.0.1
      with:
        FILE_PATTERNS: |
          changelog.rst
        TARGET_ROOT: |
          docsrc/
        TARGET_REPOS: |
          PharaohCola13/pmat-docs-test:docs
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
