name: Sync Changelog
on:
  push:
    paths:
      - changelog.rst
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run GitHub File Sync
      uses: adrianjost/files-sync-action@v1.0.1
      with:
        FILE_PATTERNS: |
          changelog.rst
        TARGET_REPOS: |
          PharaohCola13/pmat-docs
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
