name: publish
on:
  push:
  workflow_dispatch:
jobs:
  publish_pmat_package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Deployment Branch
      uses: actions/checkout@master
      with:
       ref: deployment
    - name: Checkout Deployment Branch
      uses: actions/checkout@master
      with:
        ref: master
        path: main
    - name: Login to GHCR
      run: |
        echo $CR_PAT | docker login ghcr.io -u physicsgoddess1972 --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_TOKEN }}
    - name: Transfer src files
      run: |
        ls main/
        mv main/src/model.r src/model.r
        mv main/src/run.sh src/run.sh
        mv main/src/util/*.py src/util/
        rm -r main
    - name: Build and Publish the PMAT Package
      run: |
        docker build . --tag ghcr.io/physicsgoddess1972/pmat:latest
        docker push ghcr.io/physicsgoddess1972/pmat:latest
