name: publish
on:
  push:
  workflow_dispatch:
jobs:
  publish_pmat_package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Deployment Branch
      uses: actions/checkout@master
      with:
       ref: deployment
    - name: Checkout src files
      run: |
        git checkout master -- src/model.r
        git checkout master -- src/run.sh
        git checkout master -- src/util/data_import.py
        git checkout master -- src/util/mesowest.py
        git checkout master -- src/util/http_util.py
        git checkout master -- src/instruments.py
    - name: Login to GHCR
      run: |
        echo $CR_PAT | docker login ghcr.io -u physicsgoddess1972 --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_TOKEN }}
    - name: Build and Publish the PMAT Package
      run: |
        docker build . --tag ghcr.io/physicsgoddess1972/pmat:latest
        docker push ghcr.io/physicsgoddess1972/pmat:latest
