# This is a basic workflow to help you get started with Actions

name: New Mexico CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0.1'
#    - name: Install Dependencies
#      run: |
#        sudo apt install gfortran libbz2-dev libv8-dev libcurl4-openssl-dev libxml2-dev libssl-dev unzip libfontconfig1-dev
#        sudo apt install zlib1g-dev libpcre3-dev liblzma-dev python3-pip python3-dev g++ libgit2-dev default-jdk libharfbuzz-dev libfribidi-dev
#        sudo apt install libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
    - name: Query dependencies
      run: |
          sudo R -e "install.packages('remotes', repos='https://cran.rstudio.com/')"
          sudo R -e "saveRDS(remotes::dev_package_deps(dependencies = TRUE), '.github/depends.Rds', version = 2)"
#          sudo R -e "writeLines(sprintf('R-%i.%i', getRversion()$major, getRversion()$minor), '.github/R-version')"
    - name: Cache R packages
      uses: actions/cache@v1
      with:
        path: ${{ env.R_LIBS_USER }}
        key: r-${{ hashFiles('DESCRIPTION') }}
    - name: install R packages
      run: |
        sudo R -e "install.packages('argparse', repos='https://cran.rstudio.com/')"
        sudo R -e "install.packages('devtools', repos='https://cran.rstudio.com/', dependencies=TRUE)"
        sudo R -e "devtools::install_version('plotrix', version='3.5', repos='https://cran.rstudio.com/')"
        sudo R -e "install.packages('RColorBrewer', repos='https://cran.rstudio.com/')"
        sudo R -e "install.packages('Metrics', repos='https://cran.rstudio.com/')"
        sudo R -e "install.packages('pacviz', repos='https://cran.rstudio.com/')"
        sudo R -e "install.packages('Hmisc', repos='https://cran.rstudio.com/')"
    - name: Run New Mexico Plot sequence
      run: cd src && bash run.sh -a -id "socorro_nm"
    - name: stage changed files
      run: git add *
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Testing CI implementation" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
