name: Testing PMAT
on:
  workflow_run:
    workflows: ["Update PMAT"]
    types: [completed]  
  workflow_dispatch:

jobs:
  globaltesting:
    name: Global tests
    strategy:
      matrix:
        datadirs: [data_large, data_small, data_small_sd]
    runs-on: ubuntu-latest
    steps:
      - name: Starting global tests
        run: |
          echo ${{matrix.datadirs}}
      - name: Checkout Master
        uses: actions/checkout@master
        with:
          ref: master
      - name: Starting global tests
        run: echo ${{matrix.datadirs}}
      - name: PMAT testing with ${{matrix.datadirs}} (clear sky)
        uses: docker://ghcr.io/physicsgoddess1972/pmat:unstable
        with:
          dir: ${{github.workspace}}/tests/data/${{matrix.datadirs}}
          out: ${{github.workspace}}/tests/data/out/${{matrix.datadirs}}
          flags: "-all -u"
      - name: PMAT testing with ${{matrix.datadirs}} (overcast)
        uses: docker://ghcr.io/physicsgoddess1972/pmat:unstable
        with:
          dir: ${{github.workspace}}/tests/data/${{matrix.datadirs}}
          out: ${{github.workspace}}/tests/data/out/${{matrix.datadirs}}
          flags: "-all -o -u"
  globalnopes:
    needs: globaltesting
    name: Global Fails
    strategy:
      matrix:
        datadirs: [no_cool, no_data, no_yaml]
    runs-on: ubuntu-latest
    steps:
      - name: Starting global tests
        run: |
          echo ${{matrix.datadirs}}
      - name: Checkout Master
        uses: actions/checkout@master
        with:
          ref: master
      - name: Starting global tests
        run: echo ${{matrix.datadirs}}
      - name: PMAT testing with ${{matrix.datadirs}} (clear sky)
        uses: docker://ghcr.io/physicsgoddess1972/pmat:unstable
        with:
          dir: ${{github.workspace}}/tests/data/data_errs/${{matrix.datadirs}}
          out: ${{github.workspace}}/tests/data/out/${{matrix.datadirs}}
          flags: "-all -u"
      - name: PMAT testing with ${{matrix.datadirs}} (overcast)
        uses: docker://ghcr.io/physicsgoddess1972/pmat:unstable
        with:
          dir: ${{github.workspace}}/tests/data/data_errs/${{matrix.datadirs}}
          out: ${{github.workspace}}/tests/data/out/${{matrix.datadirs}}
          flags: "-all -o -u"
  publish_pmat_package:
    needs: globalnopes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Deployment Branch
      uses: actions/checkout@master
      with:
       ref: deployment
    - name: Login to GHCR
      run: |
        echo $CR_PAT | docker login ghcr.io -u physicsgoddess1972 --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_TOKEN }}
    - name: Build and Publish the Stable PMAT Package
      run: |
        docker build . --tag ghcr.io/physicsgoddess1972/pmat:stable
        docker push ghcr.io/physicsgoddess1972/pmat:stable
