# name: Releases

# on: 
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         ref: docs
#     - name: define vars
#       run: |
#         prev=$(cat ./util/changelog.yml | grep version | head -n 2 | cut -d':' -f 2 | sed -n 2p | xargs)
#         version=$(cat ./util/changelog.yml | grep version | head -n 1 | cut -d':' -f 2 | sed -n 1p | xargs)
#         echo 'release='$(cat ./util/changelog.yml | grep released | head -n 1 | cut -d':' -f 2 | sed -n 1p | xargs) >> $GITHUB_ENV       
#         echo 'name='$(cat ./util/changelog.yml | grep name | head -n 1 | cut -d':' -f 2 | sed -n 1p | xargs) >> $GITHUB_ENV 
#         echo 'body='$(sed -n -e "/id='$version'/,/id='$prev'/p" ./CHANGELOG.md) >> $GITHUB_ENV
#         echo 'version='$version >> $GITHUB_ENV

#     # - name: Generate Citation
#     #   run: |
#     #     title="Precipitable-water Model Analysis Tool"
#     #     author_lst=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/physicsgoddess1972/Precipitable-Water-Model/contributors | grep "login" | cut -d ":" -f2 | tr -d '"' | tr -d ',')
#     #     authors=()
#     #     for i in $author_lst; do
#     #     peeps=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/users/$i | grep '"name"' | cut -d ":" -f2 | tr -d '"')

#     #     if [[ "$peeps" != *"null"* ]]; then
#     #     authors+=("${peeps}")
#     #     fi
#     #     done

#     #     authors[-1]=$(echo ${authors[-1]} | tr -d ",")

#     #     release_tag=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/physicsgoddess1972/Precipitable-Water-Model/releases/latest | grep "tag_name" | cut -d ":" -f2 | tr -d '"' | tr -d ',' | tr -d ' ')
#     #     date=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/physicsgoddess1972/Precipitable-Water-Model/releases/latest | grep "published_at" | cut -d ":" -f2 | tr -d '"' | tr -d ',')

#     #     year=$(echo $date | cut -d "-" -f1 )
#     #     month=$(echo $date | cut -d "-" -f2 )
#     #     day=$(echo $date | cut -d "-" -f3 | cut -d "T" -f1)

#     #     address="Socorro, NM"
#     #     doi="10.5281/zenodo.4587475"

#     #     bibtex="@software{pmat:$year,
#     #                 \n\ttitle={$title},
#     #                 \n\tauthor={${authors[@]}},
#     #                 \n\tversion={$release_tag},
#     #                 \n\taddress={$address},
#     #                 \n\tyear={$year},
#     #                 \n\tmonth={$month},
#     #                 \n\tday={$day},
#     #                 \n\tdoi={$doi}\n}"
#     #     echo -e $bibtex > ./CITATION.bib
#     - name: Create a GitHub release
#       if: env.release == 'yes'
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: "v${{ env.version }}"
#         release_name: ${{ env.name }} 
#         body: ${{ env.body }}