name: Releases

on: 
  push:
    paths:
      - CHANGELOG.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: define vars
      run: |
        prev=$(cat ./util/changelog.yml | grep version | head -n 2 | cut -d':' -f 2 | sed -n 2p | xargs)
        version=$(cat ./util/changelog.yml | grep version | head -n 1 | cut -d':' -f 2 | sed -n 1p | xargs)
        echo 'release='$(cat ./util/changelog.yml | grep released | head -n 1 | cut -d':' -f 2 | sed -n 1p | xargs) >> $GITHUB_ENV       
        echo 'name='$(cat ./util/changelog.yml | grep name | head -n 1 | cut -d':' -f 2 | sed -n 1p | xargs) >> $GITHUB_ENV 
        echo 'body='$(sed -n -e "/id='$version'/,/id='$prev'/p" ./CHANGELOG.md) >> $GITHUB_ENV
        echo 'version='$version >> $GITHUB_ENV
    - name: test
      run: |
        echo ${{ env.release }} 
    - name: Create a GitHub release
      if: env.release == 'yes'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.version }}"
        release_name: ${{ env.name }} 
        body: ${{ env.body }}
