# This is a basic workflow to help you get started with Actions

name: South Dakota Plots CI

# Controls when the action will run.
on:
  push:
    paths:
      - 'data/rapidcity_sd/master_data.csv'
  workflow_dispatch:

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0.1'
    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt upgrade
        sudo apt install gfortran libbz2-dev libv8-dev libcurl4-openssl-dev libxml2-dev libssl-dev libfontconfig1-dev
        sudo apt install zlib1g-dev libpcre3-dev liblzma-dev g++ libgit2-dev default-jdk libharfbuzz-dev libfribidi-dev
        sudo apt install libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
    - name: Query dependencies
      run: |
        install.packages('remotes')
        saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}
    - name: Cache R packages
      if: runner.os != 'Windows'
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-cache-v2-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
    - name: install R packages
      run: |
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}
    - name: Run New Mexico Plot sequence
      run: cd src && bash run.sh -a -id "rapidcity_sd"
    - name: stage changed files
      run: git add *
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Generating South Dakota Plots" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
