name: Testing PMAT
on:
  push:
    paths:
      - "src/*.r"
      - "src/*.py"
      - "DESCRIPTION"
      - "requirements.txt"
  workflow_dispatch:

jobs:
  global:
    name: Global tests
    strategy:
      matrix:
        datadirs: [data_large, data_small, data_small_sd, data_errs/no_cool, data_errs/no_data, data_errs/no_yaml]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
        with:
          ref: master
      - name: Starting global tests
        run: echo ${{matrix.datadirs}}
      - name: PMAT testing with ${{matrix.datadirs}} (clear sky)
        uses: docker://ghcr.io/physicsgoddess1972/pmat:latest
        with:
          dir: ${{github.workspace}}/tests/data/${{matrix.datadirs}}/
          out: ${{github.workspace}}/tests/out/${{matrix.datadirs}}/
          flags: "-all -u"
      - name: PMAT testing with ${{matrix.datadirs}} (overcast)
        uses: docker://ghcr.io/physicsgoddess1972/pmat:latest
        with:
          dir: ${{github.workspace}}/tests/data/${{matrix.datadirs}}/
          out: ${{github.workspace}}/tests/out/${{matrix.datadirs}}/
          flags: "-all -o -u"