name: Update src files
on:
  push:
  workflow_dispatch:
jobs:
  update_src:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Deployment Branch
      uses: actions/checkout@master
      with:
       ref: deployment
    - name: Checkout Master Branch
      uses: actions/checkout@master
      with:
        ref: master
        path: main
    - name: Transfer files
      run: |
        mkdir -p ./src/util
        mv ./main/src/model.r ./src/
        mv ./main/src/run.sh ./src/
        mv ./main/src/util/*.py ./src/util/
    - name: Add and commit
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: Updating src files
        add: './src/*'
        branch: deployment
