name: Update PMAT
on:
  push:
    paths:
      - "src/*.r"
      - "src/*.py"
      - "src/run.sh"
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Deployment Branch
      uses: actions/checkout@master
      with:
       ref: deployment
    - name: Checkout Master Branch
      uses: actions/checkout@master
      with:
        ref: master
        path: main
    - name: Transfer files
      run: |
        mkdir -p ./src/util
        mv ./main/src/*.r ./src/
        mv ./main/src/run.sh ./src/
        mv ./main/src/*.py ./src/
    - name: Add and commit
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: Updating src files
        add: './src/*'
        branch: deployment
  sync:
    needs: update 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Run GitHub File Sync
      uses: adrianjost/files-sync-action@v1.0.1
      with:
        FILE_PATTERNS: |
          src/pmat_.*
        TARGET_REPOS: |
          PharaohCola13/pmat-docs
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  publish_pmat_package:
    needs: sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Deployment Branch
      uses: actions/checkout@master
      with:
       ref: deployment
    - name: Login to GHCR
      run: |
        echo $CR_PAT | docker login ghcr.io -u physicsgoddess1972 --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_TOKEN }}
    - name: Build and Publish the PMAT Package
      run: |
        docker build . --tag ghcr.io/physicsgoddess1972/pmat:latest
        docker push ghcr.io/physicsgoddess1972/pmat:latest
