- instruments:
  - sensor:
      name:
      error:
      color:
      ratio:
      range:
      emissivity:
      poster:
      active:
- analysis:
  - train_fraction:
  - rel_difference:
  - iteration:
      step:
      seed:
- logging:
  - verbose:
- import:
  - external:
  - mesowest:
    - id:
  - wyoming:
    - id:
      weight: