- sensor:
    name:
    error:
    color:
    ratio:
    range:
    emissivity:
    poster:
    active:
- train_fraction:
  value:
- rel_difference:
  value:
---
- mesowest:
  - id:
- wyoming:
  - id:
  - id: