- instruments:
  - sensor:
      name:
      error:
      color:
      ratio:
      range:
      emissivity:
      poster:
      active:
- analysis:
  - train_fraction:
  - rel_difference:
  - iteration:
      step:
      seed:
- logging:
  - verbose:
- style:
    - pw_label:
- import:
  - external:
      - pw:
          - id:
            path:
            weight:
            date:
            merge:
            units:
      - rh:
          - id:
            path:
            weight:
            date:
            merge:
            units:
  - mesowest:
    - id:
  - wyoming:
    - id:
      weight: