- sensor:
    name:
    error:
    color:
    ratio:
    range:
    emissivity:
    poster:
    active:
- analysis:
  - train_fraction: 0.8
  - rel_difference: 2
  - iteration:
      step: 10
      seed:
- logging:
  - verbose: 0
- import:
  - external:
      - pw:
          - id:
            path:
            weight:
            date:
            merge:
            units:
  - mesowest:
    - id:
  - wyoming:
    - id:
      weight:
    - id:
      weight: